openapi: 3.0.1
info:
  title: maven_workflow
  description: This is sample maven template
  x-cortex-tag: maven_workflow
  x-cortex-type: service
  x-cortex-git:
    github:
      repository: ftvc-org/maven_workflow
  x-cortex-static-analysis:
    sonarqube:
      alias: SonarCloud
      project: ftvc-org_maven_workflow
